
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 12 11:41:36 CET 2014
//----------------------------------------------------

package calculator;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int MIB = 13;
  public static final int DOD = 9;
  public static final int SILENCE = 25;
  public static final int SOL = 18;
  public static final int PLAY = 6;
  public static final int EOLN = 4;
  public static final int END = 3;
  public static final int SIB = 23;
  public static final int FAD = 16;
  public static final int RED = 12;
  public static final int ID = 7;
  public static final int FA = 15;
  public static final int RE = 11;
  public static final int REB = 10;
  public static final int DO = 8;
  public static final int BEGIN = 2;
  public static final int LA = 21;
  public static final int SOLD = 19;
  public static final int SOLB = 17;
  public static final int COMMA = 5;
  public static final int FLOAT = 27;
  public static final int EOF = 0;
  public static final int MI = 14;
  public static final int SI = 24;
  public static final int LAD = 22;
  public static final int error = 1;
  public static final int LAB = 20;
  public static final int INTEGER = 26;
}

